version: "3"
services: 
    mysql:
        build: ./mysql/
        volumes: 
            - ./mysql/db:/docker-entrypoint-initdb.d
        image: mysql:latest
        environment: 
            - MYSQL_ROOT_PASSWORD=****